os:
  - linux
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
before_install:
  - composer self-update
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive
install:
  - travis_retry composer install --no-interaction --prefer-source
  - phive --no-progress install --trust-gpg-keys 4AA394086372C20A phpunit@^5.7
script: ./tools/phpunit
notifications:
  email: false